#!/home/ubuntu/Development/devsecops/bin/python
message = "Assignment Feb 21st"

#what is the output of the following code
def calculate (num1, num2=4):
  res = num1 * num2
  print(res)
calculate(5, 6)
#Ans = 30

#What is the output of the following code?
var = "James" * 2  * 3
print(var)
#Ans = JamesJamesJamesJamesJamesJames

#what is the output of the following code
x = 36 / 4 * (3 +  2) * 4 + 2
print(x)
#Ans = 182.0


#What is the output of the following code
var1 = 1
var2 = 2
var3 ="3"
print(var + var2 + var3)
#Ans = Throws an error. can only concatenate str to str 

#what is the output of the following code?
p, q, r = 10, 20 ,30
print(p, q, r)
#Ans = Code didn't run.


if __name__ =="__main__": #this ensures that this script only runs from the command line
    print(message)

